### ISSUE TITLE
Suggestion: Do away with semicolons

### ISSUE THREAD

**Issue by dar5hak** [Feation/Feation#10] opened 2015-09-03 09:10 UTC
...Or make them mandatory. Optional semicolons require extra parsing effort in `ast.js`, and moreover, users can potentially mix-and-match semicolons, which is not good.

**Comment by danilolekovic** [comment] 2015-09-03 09:53
I see, but I feel like the users should feel empowered having the decision to use semicolons or not :smiley: You are correct and that could be a problem, can't decide whether or not to keep them, remove them, or have both newlines and semicolons.

**Comment by dar5hak** [comment] 2015-09-04 06:52
True, but then semicolons don't really serve any purpose, since people are going to use newlines anyway. If anything, they only take up more bytes. (This is, of course, just my opinion.)

**Comment by mikebolt** [comment] 2015-09-05 06:12
I would like to make sure you are all aware of the pros and cons of each possible solution to this problem.

1. Do not require semicolons.

  This is how JavaScript works. Semicolons are not always necessary but are often required in order to remove ambiguities. Consider the following snippet of JavaScript:

    `fun()`
    `[1].sort()`

  The JavaScript interpreter sees two statements: the `fun()` statement and the `[1].sort` statement. But what if you wrote something like this:

    `veryLongFunctionNameThatShouldHaveALineBreakAfterIt()`
        `[1].sort()`

  The JavaScript interpreter will also parse this as two statements, but you probably meant for it to  parse a single statement like this:

     `veryLongFunctionNameThatShouldHaveALineBreakAfterIt()[1].sort()`

  This is just one example of an ambiguity and there are lots of others. The problem isn't with making semicolons optional, but with making semicolons optional *and* using newlines to format the code. In that case the parser faces a decision every time it sees a newline: "Is this the end of a statement or not?" JavaScript makes this decision by using "Automatic Semicolon Insertion" which seems to have upset many developers due to being non-intuitive. It also technically isn't a solution to this problem, because it still requires semicolons to be placed in some cases in order to avoid ambiguities. There's lots of literature on JavaScript's automatic semicolon insertion that should convince you that it isn't a great solution.

  The real solution would be to make statements themselves non-ambiguous, such that they don't require any terminating character (newline, semicolon, or otherwise). Some functional languages like Lisp manage this by using parentheses and having the final closing parenthesis indicate the end of the expression-statement. I wish there were some easy way to make clean-looking statements that were unambiguous, but unfortunately this represents a very difficult problem from a language design perspective. It means that no suffix of a valid statement may be a valid statement.

  Another solution is to require some kind of token to start every statement. Some people may see this as equivalent to requiring semicolons, but it would at least remove the ambiguities.

2. Do not allow semicolons.

  You have all the problems of not requiring semicolons with none of the benefits. In any case where there can be an ambiguity due to newlines, there will be.

3. Require semicolons to terminate statements.

  This is how C and Java handle newlines. Newlines are thus just another kind of whitespace and may be completely ignored after tokenizing. Style is completely separated from function. You can place as many newlines as you want between any kind of token and format your code as you see fit. Newlines can't cause any ambiguities because the parser always knows to keep parsing the current statement until it sees a semicolon.

I think it is clear that I prefer option 3, but I hope that this is helpful.

**Comment by dar5hak** [comment] 2015-09-05 13:53
@mikebolt Thank you for the insights. This explains a lot.

Additional point: If we were to go with option 2, a way out would be to enforce indentation, like Python, but that would also mean extra parsing effort. Over to @danilolekovic.

**Comment by danilolekovic** [comment] 2015-09-06 01:42
@mikebolt @dar5hak Thanks guys! I'm really trying to stay far, far away from indentation. I am currently considering removing semicolons completely.

**Closed** 2015-09-20 22:02 UTC
